#! /bin/bash
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 1
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 2
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 3
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 4
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 5
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 6
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 7
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 8
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 9
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 10
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 11
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 12
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 13
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 14
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 15
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 16
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 17
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 18
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 19
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 20
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 21
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 22
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 23
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 24
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 25
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 26
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 27
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 28
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 29
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 30
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 31
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 32
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 33
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 34
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 35
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 36
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 37
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 38
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 39
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 40
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 41
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 42
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 43
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 44
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 45
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 46
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 47
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 48
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 49
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 50
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 51
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 52
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 53
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 54
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 55
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 56
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 57
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 58
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 59
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 60
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 61
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 62
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 63
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 64
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 65
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 66
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 67
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 68
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 69
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 70
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 71
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 72
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 73
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 74
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 75
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 76
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 77
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 78
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 79
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 80
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 81
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 82
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 83
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 84
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 85
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 86
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 87
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 88
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 89
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 90
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 91
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 92
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 93
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 94
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 95
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 96
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 97
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 98
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 99
java -Xmx7G -jar ./build/libs/real-time-search-1.0-SNAPSHOT.jar 100
