package edu.unh.cs.ai.realtimesearch.environment

enum class Domains {
    ACROBOT,
    GRID_WORLD,
    POINT_ROBOT,
    POINT_ROBOT_LOST,
    POINT_ROBOT_WITH_INERTIA,
    RACETRACK,
    AIRSPACE,
    VACUUM_WORLD,
    HEAVY_VACUUM_WORLD,
    TRAFFIC,
    LIFE_GRIDS,
    SLIDING_TILE_PUZZLE_4,
    SLIDING_TILE_PUZZLE_4_HEAVY,
    SLIDING_TILE_PUZZLE_4_INVERSE,
    SLIDING_TILE_PUZZLE_4_SQRT
}